### ISSUE TITLE
byte java object cannot be cast to bukkit blockdata movecraft 7.0.0

### ISSUE THREAD

**Issue by TheHappyHopper** [eirikh1996/Movecraft#110]
**Describe the bug**
Using a stick in game will move the ship once then stop working

**To Reproduce**
1. build a ship
2. Pilot the ship
3. Move the ship
4. try to move the ship again
5. Ship refuses to move again

**Expected behavior**
1. build a ship
2. Pilot the ship
3. Move the ship
4. try to move the ship again
5. Ship moves again

**Versions (please complete the following information):**
 - Movecraft: [Movecraft 7.0.0 for 1.8.8 to 1.16.5]
 - Java [1.8.0_281]
 - Minecraft [1.16.5]
 - Server [paper-1.16.5-576]

Error:
[09:44:40 WARN]: [Movecraft] Task #509 for Movecraft v7.0.0_for_1.8.8-1.16.2 generated an exception
java.lang.ClassCastException: java.lang.Byte cannot be cast to org.bukkit.block.data.BlockData
        at net.countercraft.movecraft.utils.WaterlogUtils.waterlogBlocksOnCraft(WaterlogUtils.java:27) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:268) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1413) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1328) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1116) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_281]

My analysis of the problem:
org.bukkit.block.data.BlockData should be a boolean according to bukkit but the byte is being cast as an int, this appears to be the issue

**Comment by wolfebersahd** [comment]
I'm having the same issue.

**Comment by Vic3x** [comment]
I'm having the same issue.

**Comment by eirikh1996** [comment]
Fixed in version 7.0.0.2
