### ISSUE TITLE
Error occurred while enabling Movecraft

### ISSUE THREAD

**Issue by JAGUARAVI** [eirikh1996/Movecraft#114]
```[15:02:21 ERROR]: Error occurred while enabling Movecraft v7.0.0.1_for_1.8.8-1.16.2 (Is it up to date?)
java.lang.IllegalArgumentException: Numerical block IDs are not supported by this version
        at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:117) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[patched_1.16.5.jar:git-Paper-576]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:415) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:580) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:280) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1055) ~[patched_1.16.5.jar:git-Paper-576]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-576]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]```

**Comment by TrollyLoki** [comment]
Check your config.yml, it probably has numbers in the `DisableShadowBlocks`. For some reason the default config still has numbers in it even though it causes that error.
