### ISSUE TITLE
Cruise is not doing cruise

### ISSUE THREAD

**Issue by MRillyt** [eirikh1996/Movecraft#117]
So Cruise doesn't seem to want to work. I'm using latest release, got this in console.
01.05 06:18:23 [Server] ERROR Could not pass event PlayerInteractEvent to Movecraft v7.0.0.1_for_1.8.8-1.16.2
01.05 06:18:23 [Server] INFO java.lang.ClassCastException: org.bukkit.material.MaterialData cannot be cast to org.bukkit.material.Sign
01.05 06:18:23 [Server] INFO at net.countercraft.movecraft.sign.CruiseSign.onSignClick(CruiseSign.java:66) ~[?:?]
01.05 06:18:23 [Server] INFO at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor46.execute(Unknown Source) ~[?:?]
01.05 06:18:23 [Server] INFO at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:531) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerInteractManager.a(PlayerInteractManager.java:498) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1698) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:32) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.PacketPlayInUseItem.a(PacketPlayInUseItem.java:10) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:35) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1252) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1245) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1120) ~[patched_1.16.5.jar:git-Paper-585]
01.05 06:18:23 [Server] INFO at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-585]

I have no clue what this is...

**Comment by AviDoesDev** [comment]
same issue..
