### ISSUE TITLE
Movecraft crash with 1.14.4

### ISSUE THREAD

**Issue by BobbyKilkins** [eirikh1996/Movecraft#18]
I am using the latest release of this fork with a recent release of Paper 1.14.4
Movecraft crashes on launch
Here is the exception:
`[14:49:27 ERROR]: Error occurred while enabling Movecraft v7.0.0_beta_1 (Is it up to date?)
java.lang.IllegalArgumentException: Numerical block IDs are not supported by this version
	at net.countercraft.movecraft.Movecraft.onEnable(Movecraft.java:153) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:338) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:420) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugin(CraftServer.java:467) ~[patched_1.14.4.jar:git-Paper-225]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.enablePlugins(CraftServer.java:381) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:474) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:290) ~[patched_1.14.4.jar:git-Paper-225]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:876) ~[patched_1.14.4.jar:git-Paper-225]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
`
I am sure I am doing something wrong since I remember this fork worked a while ago on spigot for me, but what is it?
Thank you for your time :D

**Comment by BobbyKilkins** [comment]
Also please tell me if you need more information like the specific paper version and other plugins on the server.

**Comment by eirikh1996** [comment]
That seems like it is trying to load a malformed config

**Comment by eirikh1996** [comment]
Try checking the PilotTool in config

**Comment by BobbyKilkins** [comment]
That fixed it, I changed the pilot tool to "stick", I was using the default config though it shouldn't do that

**Comment by eirikh1996** [comment]
Looks like it replaced string IDs with numerical ones after merging the upstream repo into mine. I am currently working on fixing that
