### ISSUE TITLE
Various redstone components break/crash movecraft

### ISSUE THREAD

**Issue by UAVwaffle** [eirikh1996/Movecraft#60]
whenever I try to move a ship with a button on it (there are several components that cause this bug, but for now I will just say button because that is one of the ones that cause this) the ship will move once, but I will not move with it and the craft won't do anything.  If I /release the craft then activate/mount/drive the ship again the same bug occurs until the button is removed.

checking in my servers log I get this bug report: comment have been added to explain proccess with a # comment here
[16:29:18] [Server thread/INFO]: [Movecraft] Player UAVwaffle piloted a craft of type PodRacer with size 84 at location: 813 x, -79 z #piloting the craft

#moving the craft  -- note: It happens regardless if I use a stick to move or use cruise: off/on
[16:29:20] [Server thread/WARN]: [Movecraft] Task #8 for Movecraft v7.0.0_for_1.8.8-1.16.1_beta_28 generated an exception
java.lang.NoSuchMethodError: net.minecraft.server.v1_16_R1.WorldServer.notifyAndUpdatePhysics(Lnet/minecraft/server/v1_16_R1/BlockPosition;Lnet/minecraft/server/v1_16_R1/Chunk;Lnet/minecraft/server/v1_16_R1/IBlockData;Lnet/minecraft/server/v1_16_R1/IBlockData;Lnet/minecraft/server/v1_16_R1/IBlockData;I)V
        at net.countercraft.movecraft.compat.v1_16_R1.IWorldHandler.processRedstone(IWorldHandler.java:279) ~[?:?]
        at net.countercraft.movecraft.compat.v1_16_R1.IWorldHandler.translateCraft(IWorldHandler.java:207) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.update.CraftTranslateCommand.doUpdate(CraftTranslateCommand.java:133) ~[?:?]
        at net.countercraft.movecraft.mapUpdater.MapUpdateManager.run(MapUpdateManager.java:62) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1061) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:354) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1009) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:848) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-c3a49df-2f18108]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[16:29:27] [Server thread/INFO]: UAVwaffle issued server command: /release #end of report

**Versions**
 - Movecraft 7.0.0 for 1.8.8 - 1.16.1 beta 28
 - Java idk will check if needed
 - Minecraft 1.16.1

**Additional context**
It's seems to happen regardless of ship type and build shape

Here is a .zip file containing the .jar i'm using and all my settings files/ship files

[Movecraft.zip](https://github.com/eirikh1996/Movecraft/files/4907571/Movecraft.zip)

**Comment by eirikh1996** [comment]
Fixed in 04276145bff4d2d8c24902dde3feeab3207bea96 and ea91b716681f3e442eff012f0c1d2568520cce3a

**Comment by UAVwaffle** [comment]
thx. I noticed on the new update it says latest 1.15.2, but I tested it and it works on 1.16.1 was that a typo error or did you on purpose thanks again
